#!/usr/bin/python3
round = 0
answer = " "

while round < 3 and answer.lower() != "brian" and answer.lower() != "shrubbery":
    round += 1     # increase the round counter by 1
    answer = input('Finish the movie title, "Monty Python\'s The Life of ______": ')
    if answer.lower() == "shrubbery":
        print("wow you are so super cool and gave the secret answer and the whole word loves you")
        break
    if answer.lower() == "brian": # logic to check if user gave correct answer
        print("Correct!")
    elif round == 3:    # logic to ensure round has not yet reached 3
        print("Sorry, the answer was Brian.")
    else:                 # if answer was wrong
        print("Sorry. Try again!")
